### PR TITLE
Refactor weather app to use basic `DataManager` and `Config` objects

### PR DESCRIPTION
**Pull request by mmaelicke**
With this PR in place, the new and highly important `DataManager` is used throughout the weather app. This should prioritize singleton usage throughout the whole streamlit instance. This should really speed things up, but make user uploads a hell more complicated, which we don't use anyway.

@AlexDo1  you could checkout this branch and run the state of this branch to report issues and errors back. These errors should then be resolved with the next release.

### CODE REVIEW

**Comment by AlexDo1** [comment]
For some reason the tests are no longer running on Github, what did I do wrong?
On my laptop now only the topic_selector test does not run successfully and I'm not sure how to do that either, because I would have to read out the session_state in the test (?), I don't know how to do that.
Can you take over @mmaelicke ?

**Comment by mmaelicke** [comment]
Ah, yeah. I broke that.

**Comment by AlexDo1** [comment]
Hm there's the old xarray IO backend error again.
Locally on my machine the weather test works..

**Comment by mmaelicke** [comment]
I removed the `topic_selector` tests altogether. I can't find any working way to mock a session state. Without that, unittesting anything relying on the state does just not work.

**Comment by mmaelicke** [comment]
> Hm there's the old xarray IO backend error again. Locally on my machine the weather test works..

Yeah, found the issue. There was a test that used the default config and not the test config. Thus, it was trying to load the original data, not the test data, which is not available in GH actions. Should be fixed now.

**Comment by mmaelicke** [comment]
Nice, unittest are running now. I will merge

**Pull request merged**
