### PR TITLE
Add Sunburst plot instead of Bubble plot

### PR DESCRIPTION
**Pull request by mmaelicke**
@AlexDo1, 

I implemented the sunburst plot into your bubble_plot branch. The plot is shown on the trasition page from weather explorer to climate explorer, and in the climate explorer itself. 
The infobox still needs translation and a better text. That's something for later.

Please review the stuff and, if you like it, we can get rid of the bubble plot routine before merging into the main branch.

### CODE REVIEW

**Comment by mmaelicke** [comment]
And btw, I found a way to fix the percentage numbers. Maybe the most over-engineered piece of code I ever wrote :)

**Review by AlexDo1 — CHANGES_REQUESTED** [review]
I really like the new sunburst plot, everything works perfectly.

I just think we need a more detailed explanation of the plot for the final version.

Great that you managed to display the percentages, I just found a small bug with the hovertext display in the innermost circle:
image

The hovertext of the other circles looks good and does not show `{customdata[1]}`

**Comment by mmaelicke** [comment]
I think the problem was, that these labels were empty ( due to missing parent category). Now, I added a `'-'`, which should fix things. Thanks for pointing out.

**Comment by mmaelicke** [comment]
Yeah, I don't have a good idea how we can come around this so far. The page might change anyway, so I would postpone this

**Pull request merged**
